#debug: true # 是否开启debug模式，debug模式下，springboot会输出更多的日志，这与自己编写的代码无关
server:
  port: 8022
    #logging:
    #  #file: logback-demo.log # 输出到项目目录下
    #  #path: /logdemo
    #  level:
  #    com.example.logbackdemo: debug
  #root: warn # root日志以warn级别输出，不要用debug模式！！---会卡的！
  #config: 'classpath:logback-spring-dev.xml' # 指定自定义的Logging配置文件，通过这个配置
  #Location of the logging configuration file. For instance, `classpath:logback.xml` for Logback.